/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HospitalAdmin;

import AddCommunity.*;
import Validations.Validations;
import javax.swing.JOptionPane;
import models.Community;
import models.CommunityHistory;
import models.Hospital;
import models.HospitalHistory;
import models.VitalsHistory;

/**
 *
 * @author LENOVO
 */
public class AddHospital extends javax.swing.JPanel {

    /**
     * Creates new form AddHospital
     */
      HospitalHistory hospitalhistory;
    CommunityHistory communityhistory;
    VitalsHistory vitalshistory;
    public AddHospital(HospitalHistory hospitalhistory, CommunityHistory communityhistory,VitalsHistory vitalshistory) {
        initComponents();
         this.hospitalhistory = hospitalhistory;
        this.communityhistory = communityhistory;
        this.vitalshistory=vitalshistory;
        updateDropDownHospital();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegisterButton = new javax.swing.JButton();
        hospitalIDLabel = new javax.swing.JLabel();
        hospitalIDInput = new javax.swing.JTextField();
        hospitalNameLabel = new javax.swing.JLabel();
        hospitalNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        selectRegionLabel = new javax.swing.JLabel();
        selectRegion = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisterButton.setText("REGISTER");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        hospitalIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalIDLabel.setText("Enter HospitalID");

        hospitalIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalIDInputActionPerformed(evt);
            }
        });

        hospitalNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalNameLabel.setText("Hospital Name");

        hospitalNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalNameInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTER HOSPITAL");

        selectRegionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectRegionLabel.setText("Select Region");

        selectRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(RegisterButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(hospitalIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalNameLabel)
                                    .addComponent(selectRegionLabel))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalNameInput)
                                    .addComponent(selectRegion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalNameLabel)
                    .addComponent(hospitalNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRegionLabel)
                    .addComponent(selectRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(RegisterButton)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        String hospitalID = hospitalIDInput.getText();
        String hospitalName = hospitalNameInput.getText();
        String region = selectRegion.getSelectedItem().toString();
        if (hospitalID.isEmpty() || hospitalName.isEmpty() || region.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Data");
        }else if (Validations.ValidateName(hospitalName) == false) {
            JOptionPane.showMessageDialog(null, "Enter valid name");
        } else if (Validations.ValidateID(hospitalID) == false) {
            JOptionPane.showMessageDialog(null, "Please enter a valid HospitalID");
        }  else {
            Hospital cm = hospitalhistory.addnewHospital();
            cm.setHospitalID(hospitalID);
            cm.setName(hospitalName);
            cm.setRegion(region);
            System.out.println(cm.getHospitalID());
            JOptionPane.showMessageDialog(null, "Hospital Registered");
            hospitalIDInput.setText("");
            hospitalNameInput.setText("");
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void hospitalIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalIDInputActionPerformed

    private void hospitalNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalNameInputActionPerformed

    private void selectRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectRegionActionPerformed
     void updateDropDownHospital() {
        for (Community p : CommunityHistory.getCommunityhistory()) {
            selectRegion.addItem(p.getCommunityAdminName());
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField hospitalIDInput;
    private javax.swing.JLabel hospitalIDLabel;
    private javax.swing.JTextField hospitalNameInput;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectRegion;
    private javax.swing.JLabel selectRegionLabel;
    // End of variables declaration//GEN-END:variables
}
