/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemAdmin;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.CommunityAdminHistory;
import models.Doctor;
import models.DoctorHistory;
import models.HospitalAdminHistory;
import models.Patient;
import models.PatientHistory;
import models.PersonHistory;

/**
 *
 * @author LENOVO
 */
public class DoctorDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorDirectoryJPanel
     */
    PatientHistory patienthistory;
    PersonHistory personhistory;
    DoctorHistory doctorhistory;
    CommunityAdminHistory communityhistory;
    HospitalAdminHistory hospitalhistory;

    public DoctorDirectoryJPanel(PatientHistory patienthistory, PersonHistory personhistory, DoctorHistory doctorhistory, CommunityAdminHistory communityhistory, HospitalAdminHistory hospitalhistory) {
        initComponents();
          this.patienthistory=patienthistory;
        this.personhistory=personhistory;
        this.doctorhistory = doctorhistory;
        this.communityhistory=communityhistory;
        this.hospitalhistory=hospitalhistory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        communityLabel1 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        ViewButton = new javax.swing.JButton();
        nameInputUpdate = new javax.swing.JTextField();
        updateLabel = new javax.swing.JLabel();
        cellPhoneLabel1 = new javax.swing.JLabel();
        doctorIDUpdate = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        emailIDLabel = new javax.swing.JLabel();
        ageInputUpdate = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        addressUpdate = new javax.swing.JTextField();
        doctorIDLabel = new javax.swing.JLabel();
        communityUpdate = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctorTbl = new javax.swing.JTable();
        cellphoneNoUpdate = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        emailIdUpdate = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();
        locationUpdate = new javax.swing.JComboBox<>();
        genderUpdate = new javax.swing.JComboBox<>();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        communityLabel1.setText("Community:");

        cityLabel.setText("City:");

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ViewButton.setText("VIEW");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        updateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateLabel.setText("UPDATE");
        updateLabel.setToolTipText("");

        cellPhoneLabel1.setText("CellPhone No:");

        doctorIDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorIDUpdateActionPerformed(evt);
            }
        });

        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        emailIDLabel.setText("Email ID:");

        ageInputUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageInputUpdateActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");

        addressUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressUpdateActionPerformed(evt);
            }
        });

        doctorIDLabel.setText("Dr ID:");

        communityUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityUpdateActionPerformed(evt);
            }
        });

        ageLabel.setText("Age:");

        doctorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Email ID", "Address", "City", "CellPhone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(doctorTbl);

        genderLabel.setText("Gender:");

        emailIdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdUpdateActionPerformed(evt);
            }
        });

        addressLabel.setText("Address:");

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainLabel.setText("VIEW DOCTOR");
        mainLabel.setToolTipText("");

        locationUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "NewYork", "California" }));
        locationUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationUpdateActionPerformed(evt);
            }
        });

        genderUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        genderUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderUpdateActionPerformed(evt);
            }
        });

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(mainLabel)
                        .addGap(28, 28, 28)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(searchBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateLabel)
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(doctorIDLabel)
                                    .addComponent(ageLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(genderLabel)
                                                    .addComponent(addressLabel)
                                                    .addComponent(communityLabel1)
                                                    .addComponent(cityLabel)
                                                    .addComponent(emailIDLabel)
                                                    .addComponent(cellPhoneLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cellphoneNoUpdate)
                                                    .addComponent(communityUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(addressUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(locationUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(genderUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(doctorIDUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nameInputUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ageInputUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(UpdateButton)
                                                .addGap(76, 76, 76)))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ViewButton)
                                            .addComponent(DeleteButton))))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updateLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nameInputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doctorIDUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(ageInputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(nameLabel)
                                        .addGap(11, 11, 11)
                                        .addComponent(doctorIDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ageLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addressUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(communityUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(communityLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(locationUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cellphoneNoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellPhoneLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIDLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton)))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = doctorTbl.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Selected a Row to Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        Doctor selectedDoctor = (Doctor) model.getValueAt(selectedRowIndex, 0);
        doctorhistory.deleteDoctor(selectedDoctor);
        JOptionPane.showMessageDialog(this, "Person Deleted");
        populateTable();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void doctorIDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorIDUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorIDUpdateActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int i = doctorTbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        if (i >= 0) {
            model.setValueAt(doctorIDUpdate.getText(), i, 0);
            model.setValueAt(nameInputUpdate.getText(), i, 1);
            model.setValueAt(ageInputUpdate.getText(), i, 2);
            model.setValueAt(genderUpdate.getSelectedItem().toString(), i, 3);
            model.setValueAt(addressUpdate.getText(), i, 4);
            model.setValueAt(communityUpdate.getText(), i, 5);
            model.setValueAt(locationUpdate.getSelectedItem().toString(), i, 6);
            model.setValueAt(cellphoneNoUpdate.getText(), i, 7);
            model.setValueAt(emailIdUpdate.getText(), i, 8);
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void ageInputUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageInputUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageInputUpdateActionPerformed

    private void addressUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressUpdateActionPerformed

    private void communityUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityUpdateActionPerformed

    private void emailIdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdUpdateActionPerformed

    private void locationUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationUpdateActionPerformed

    private void genderUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderUpdateActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) doctorTbl.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(Model);
        doctorTbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchInput.getText().trim()));
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressUpdate;
    private javax.swing.JTextField ageInputUpdate;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel cellPhoneLabel1;
    private javax.swing.JTextField cellphoneNoUpdate;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel communityLabel1;
    private javax.swing.JTextField communityUpdate;
    private javax.swing.JLabel doctorIDLabel;
    private javax.swing.JTextField doctorIDUpdate;
    private javax.swing.JTable doctorTbl;
    private javax.swing.JLabel emailIDLabel;
    private javax.swing.JTextField emailIdUpdate;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> genderUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> locationUpdate;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JTextField nameInputUpdate;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
  private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        model.setRowCount(0);
        for (Doctor ps : doctorhistory.getDoctorhistory()) {
            Object[] row = new Object[8];
            row[0] = ps;
            row[1] = ps.getName();
            row[2] = ps.getAge();
            row[3] = ps.getGender();
            row[4] = ps.getEmailid();
            row[5] = ps.getAddress();
            row[6] = ps.getCity();
            row[7] = ps.getCellphoneno();
            model.addRow(row);
        }
    }
}

