/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemAdmin;
import SystemAdmin.PersonDirectoryJPanel;
import SystemAdmin.PatientDirectoryJPanel;
import SystemAdmin.AddPersonJPanel;
import SystemAdmin.DoctorDirectoryJPanel;
import models.DoctorHistory;
import models.PatientHistory;
import models.PersonHistory;
import models.CommunityAdminHistory;
import models.HospitalAdminHistory;
import ui.RegisterJFrame;

/**
 *
 * @author LENOVO
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
     PatientHistory patienthistory;
    PersonHistory personhistory;
    DoctorHistory doctorhistory;
    CommunityAdminHistory communityhistory;
    HospitalAdminHistory hospitalhistory;
    public MainJFrame(PatientHistory patienthistory, PersonHistory personhistory, DoctorHistory doctorhistory, CommunityAdminHistory communityhistory, HospitalAdminHistory hospitalhistory) {
        initComponents();
    this.patienthistory=patienthistory;
        this.personhistory=personhistory;
        this.doctorhistory = doctorhistory;
        this.communityhistory=communityhistory;
        this.hospitalhistory=hospitalhistory;}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        personDirectoryBtn = new javax.swing.JButton();
        patientDirectoryBtn = new javax.swing.JButton();
        doctorDirectoryBtn = new javax.swing.JButton();
        hospitalAdminsBtn = new javax.swing.JButton();
        communityAdminsBtn = new javax.swing.JButton();
        addPersonBtn = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        controlArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workArea.setBackground(new java.awt.Color(255, 255, 255));

        personDirectoryBtn.setBackground(new java.awt.Color(255, 153, 51));
        personDirectoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personDirectoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        personDirectoryBtn.setText("Person Directory");
        personDirectoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personDirectoryBtnActionPerformed(evt);
            }
        });

        patientDirectoryBtn.setBackground(new java.awt.Color(255, 153, 51));
        patientDirectoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientDirectoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        patientDirectoryBtn.setText("Patient Directory ");
        patientDirectoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDirectoryBtnActionPerformed(evt);
            }
        });

        doctorDirectoryBtn.setBackground(new java.awt.Color(255, 153, 51));
        doctorDirectoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctorDirectoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        doctorDirectoryBtn.setText("Doctor Directory");
        doctorDirectoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorDirectoryBtnActionPerformed(evt);
            }
        });

        hospitalAdminsBtn.setBackground(new java.awt.Color(255, 153, 51));
        hospitalAdminsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hospitalAdminsBtn.setForeground(new java.awt.Color(255, 255, 255));
        hospitalAdminsBtn.setText("Hospital Admins");
        hospitalAdminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalAdminsBtnActionPerformed(evt);
            }
        });

        communityAdminsBtn.setBackground(new java.awt.Color(255, 153, 51));
        communityAdminsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        communityAdminsBtn.setForeground(new java.awt.Color(255, 255, 255));
        communityAdminsBtn.setText("Community Admins");
        communityAdminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityAdminsBtnActionPerformed(evt);
            }
        });

        addPersonBtn.setBackground(new java.awt.Color(255, 153, 51));
        addPersonBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        addPersonBtn.setText("Add Person");
        addPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonBtnActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        controlArea.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doctorDirectoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personDirectoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientDirectoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hospitalAdminsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(communityAdminsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controlArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(addPersonBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personDirectoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientDirectoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorDirectoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospitalAdminsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(communityAdminsBtn)
                .addGap(47, 47, 47)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controlArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        splitPane.setLeftComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personDirectoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personDirectoryBtnActionPerformed
        // TODO add your handling code here:
        PersonDirectoryJPanel personPanel = new PersonDirectoryJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(personPanel);
    }//GEN-LAST:event_personDirectoryBtnActionPerformed

    private void patientDirectoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDirectoryBtnActionPerformed
        // TODO add your handling code here:
        PatientDirectoryJPanel patientPanel = new PatientDirectoryJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(patientPanel);
    }//GEN-LAST:event_patientDirectoryBtnActionPerformed

    private void doctorDirectoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorDirectoryBtnActionPerformed
        // TODO add your handling code here:
        DoctorDirectoryJPanel doctorPanel = new DoctorDirectoryJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(doctorPanel);
    }//GEN-LAST:event_doctorDirectoryBtnActionPerformed

    private void hospitalAdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalAdminsBtnActionPerformed
        // TODO add your handling code here:
        HospitalAdminJPanel personPanel = new HospitalAdminJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(personPanel);
    }//GEN-LAST:event_hospitalAdminsBtnActionPerformed

    private void communityAdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityAdminsBtnActionPerformed
        // TODO add your handling code here:
        CommunityAdminJPanel adminPanel = new CommunityAdminJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(adminPanel);
    }//GEN-LAST:event_communityAdminsBtnActionPerformed

    private void addPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonBtnActionPerformed
        AddPersonJPanel personPanel = new AddPersonJPanel(patienthistory,personhistory,doctorhistory,communityhistory,hospitalhistory);
        splitPane.setRightComponent(personPanel);// TODO add your handling code here:
    }//GEN-LAST:event_addPersonBtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        RegisterJFrame mainframe = new RegisterJFrame();
        mainframe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonBtn;
    private javax.swing.JButton communityAdminsBtn;
    private javax.swing.JPanel controlArea;
    private javax.swing.JButton doctorDirectoryBtn;
    private javax.swing.JButton hospitalAdminsBtn;
    private javax.swing.JButton logout;
    private javax.swing.JButton patientDirectoryBtn;
    private javax.swing.JButton personDirectoryBtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
