/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemAdmin;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.CommunityAdminHistory;
import models.DoctorHistory;
import models.HospitalAdminHistory;
import models.PatientHistory;
import models.Person;
import models.PersonHistory;


/**
 *
 * @author LENOVO
 */
public class PersonDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonDirectoryJPanel
     */
     PatientHistory patienthistory;
    PersonHistory personhistory;
    DoctorHistory doctorhistory;
    CommunityAdminHistory communityhistory;
    HospitalAdminHistory hospitalhistory;
    public PersonDirectoryJPanel(PatientHistory patienthistory, PersonHistory personhistory, DoctorHistory doctorhistory, CommunityAdminHistory communityhistory, HospitalAdminHistory hospitalhistory) {
        initComponents();
         this.patienthistory=patienthistory;
        this.personhistory=personhistory;
        this.doctorhistory = doctorhistory;
        this.communityhistory=communityhistory;
        this.hospitalhistory=hospitalhistory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cellPhoneLabel = new javax.swing.JLabel();
        personIDUpdate = new javax.swing.JTextField();
        cellphoneNoUpdate = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        emailIdLabel = new javax.swing.JLabel();
        emailIdUpdate = new javax.swing.JTextField();
        ageInputUpdate = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        viewpersonlabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        addressUpdate = new javax.swing.JTextField();
        locationUpdate = new javax.swing.JComboBox<>();
        DeleteButton = new javax.swing.JButton();
        personIdLabel = new javax.swing.JLabel();
        genderUpdate = new javax.swing.JComboBox<>();
        nameInputUpdate = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        personTbl = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cellPhoneLabel.setText("CellPhone No:");

        personIDUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personIDUpdateActionPerformed(evt);
            }
        });

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender:");

        emailIdLabel.setText("Email ID:");

        emailIdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdUpdateActionPerformed(evt);
            }
        });

        ageInputUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageInputUpdateActionPerformed(evt);
            }
        });

        addressLabel.setText("Address:");

        nameLabel.setText("Name:");

        viewpersonlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewpersonlabel.setText("VIEW Person");
        viewpersonlabel.setToolTipText("");

        cityLabel.setText("City:");

        addressUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressUpdateActionPerformed(evt);
            }
        });

        locationUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "NewYork", "California" }));
        locationUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationUpdateActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        personIdLabel.setText("Person ID:");

        genderUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        genderUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderUpdateActionPerformed(evt);
            }
        });

        ageLabel.setText("Age:");

        updateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateLabel.setText("UPDATE");
        updateLabel.setToolTipText("");

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        personTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Email ID", "Address", "City", "CellPhone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(personTbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(viewpersonlabel)
                        .addGap(85, 85, 85)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(searchBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(updateLabel)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(personIdLabel)
                            .addComponent(ageLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(genderLabel)
                                        .addComponent(addressLabel)
                                        .addComponent(cityLabel))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addressUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(locationUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(genderUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(121, 121, 121))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(personIDUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameInputUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ageInputUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailIdLabel)
                                                .addComponent(cellPhoneLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cellphoneNoUpdate)
                                                .addComponent(emailIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(updateBtn)
                                            .addGap(76, 76, 76)))
                                    .addGap(49, 49, 49)
                                    .addComponent(DeleteButton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpersonlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameInputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personIDUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(ageInputUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameLabel)
                        .addGap(11, 11, 11)
                        .addComponent(personIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(locationUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(DeleteButton)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cellphoneNoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellPhoneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)))
                .addContainerGap(495, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void personIDUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personIDUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personIDUpdateActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int i = personTbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) personTbl.getModel();
        if (i >= 0) {
            model.setValueAt(personIDUpdate.getText(), i, 0);
            model.setValueAt(nameInputUpdate.getText(), i, 1);
            model.setValueAt(ageInputUpdate.getText(), i, 2);
            model.setValueAt(genderUpdate.getSelectedItem().toString(), i, 3);
            model.setValueAt(addressUpdate.getText(), i, 4);
            model.setValueAt(locationUpdate.getSelectedItem().toString(), i, 5);
            model.setValueAt(cellphoneNoUpdate.getText(), i, 6);
            model.setValueAt(emailIdUpdate.getText(), i, 7);
        } else {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void emailIdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdUpdateActionPerformed

    private void ageInputUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageInputUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageInputUpdateActionPerformed

    private void addressUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressUpdateActionPerformed

    private void locationUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationUpdateActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = personTbl.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please Selected a Row to Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) personTbl.getModel();
        Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
        personhistory.deletePerson(selectedPerson);
        JOptionPane.showMessageDialog(this, "Person Deleted");
        populateTable();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void genderUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderUpdateActionPerformed

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) personTbl.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(Model);
        personTbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchInput.getText().trim()));
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressUpdate;
    private javax.swing.JTextField ageInputUpdate;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel cellPhoneLabel;
    private javax.swing.JTextField cellphoneNoUpdate;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel emailIdLabel;
    private javax.swing.JTextField emailIdUpdate;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> genderUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> locationUpdate;
    private javax.swing.JTextField nameInputUpdate;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField personIDUpdate;
    private javax.swing.JLabel personIdLabel;
    private javax.swing.JTable personTbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JLabel viewpersonlabel;
    // End of variables declaration//GEN-END:variables
  private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) personTbl.getModel();
        model.setRowCount(0);
        for (Person ps : personhistory.getPersonhistory()) {
            Object[] row = new Object[8];
            row[0] = ps;
            row[1] = ps.getName();
            row[2] = ps.getAge();
            row[3] = ps.getGender();
            row[4] = ps.getEmailid();
            row[5] = ps.getAddress();
            row[6] = ps.getCity();
            row[7] = ps.getCellphoneno();
            model.addRow(row);
        }
    }}
